name: EC2 SSH Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: [self-hosted, home]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Test Command
      run: |
        echo "This is a test from the self-hosted runner" > test.txt
        cat test.txt
