name: EC2 SSH Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH Agent
      run: |
        eval $(ssh-agent -s)

        # Directly paste your private key here
        echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAu3yigAuhhFTK340ORECaQyPiTPzxrSmZDY4mf62Ysd/83PCNUoOj
naWk/l15jjYdjztC4EeqahI0LwVlh1ec4x4p4r09DCUFwcBvx/6qq2y73r8L8Vn+tKIAPH
91rEkV/zepycce0qFTPcrTmyuhHeQyWJ/zQnx9fatZpt5wmN+36NLJpnEtwiZROyBeohX4
AVN2cm6/l6OFdc39e9tEa2jfEDZMmiqcyBzBd0WcmKQxS1DZmh5S0VhKf6t1uGzQIC17rT
ytwMZxlBmlTj79lid4SwAuA0QYNULaKyCkYtXwvCwquK52jNyXpd7SncxTawsoAlAkWHyA
fpZP7kkHLh1KkUeDsnJCgxe+09typ56d94hbRNDpnkYB4mEI+w1K00UlNIIGm4guQXSJMS
ckNZ/njhcZglw7eUQhwf/WRCxH375agJQt7eK1AdVkFpdD6UgP/hfUl6QezvCykKgiWQZq
fUvdEG90X0P59xvVy/fCS2yBjPAFxN0NZ506FYg617OqNsISFigRYXPKz001ssE5+LYMm3
MXIp382NxKrgJDFHf59xb1w0AKGwpIvNo8P9HiyRznj+PqU5mOIC5ngBaJ3lD+heBFzrAU
r5/HdD6frh5UastAu+6EACHUv6Ui9kb9DMqlu6lw176lYQQEHA4NUpgoT9ySjPSa25c33i
kAAAdImG/1r5hv9a8AAAAHc3NoLXJzYQAAAgEAu3yigAuhhFTK340ORECaQyPiTPzxrSmZ
DY4mf62Ysd/83PCNUoOjnaWk/l15jjYdjztC4EeqahI0LwVlh1ec4x4p4r09DCUFwcBvx/
6qq2y73r8L8Vn+tKIAPH91rEkV/zepycce0qFTPcrTmyuhHeQyWJ/zQnx9fatZpt5wmN+3
6NLJpnEtwiZROyBeohX4AVN2cm6/l6OFdc39e9tEa2jfEDZMmiqcyBzBd0WcmKQxS1DZmh
5S0VhKf6t1uGzQIC17rTytwMZxlBmlTj79lid4SwAuA0QYNULaKyCkYtXwvCwquK52jNyX
pd7SncxTawsoAlAkWHyAfpZP7kkHLh1KkUeDsnJCgxe+09typ56d94hbRNDpnkYB4mEI+w
1K00UlNIIGm4guQXSJMSckNZ/njhcZglw7eUQhwf/WRCxH375agJQt7eK1AdVkFpdD6UgP
/hfUl6QezvCykKgiWQZqfUvdEG90X0P59xvVy/fCS2yBjPAFxN0NZ506FYg617OqNsISFi
gRYXPKz001ssE5+LYMm3MXIp382NxKrgJDFHf59xb1w0AKGwpIvNo8P9HiyRznj+PqU5mO
IC5ngBaJ3lD+heBFzrAUr5/HdD6frh5UastAu+6EACHUv6Ui9kb9DMqlu6lw176lYQQEHA
4NUpgoT9ySjPSa25c33ikAAAADAQABAAACAAUl4XJhn2A6Uc28mkkueu3gBN03Ts2B6GVy
Y0U7N4eezlskscSzv6DbBQJE/8rzWnFt36K35Qp/kHZAEC8crT6hO+YxawUz2QoeZhNYP0
hwtmHh3gqU/YTpM9d1an4+DYAR/7P+Jy8CZf463P+UPZrMAsPjNHM9Zta2B0KpNe9EqVCX
xRiwX+DGW5GjjGWn88TZjVWMC++2ejonW0/0z9ahLQrNauIKzH5EJ93GCAw66e2W/TqZnY
2I/pat1xAm0LopdY1mrqCt8j1uTNcurJjcYZWxnhHR41ZHDSWFAm6CUFdiYRPsGm44umNA
EIlrrFiymDkkCTNyy7ZuGyjAUZWbA2vn4/GNlR6XwwsL0xhtH+1mf2hyxghYjBK66dMa4g
9KYfN5cQvIZqKOt5kBwf9LBopR9iufUBDAeJTczPcn6zEePC2vSEwuXibZayoQKtKzgUFf
IJCS5qnR3Ka2OQZsTzNBZScLTSMX8rlY2+YxZXnTpFBpTDq8bEix2hT2Cf8ENiMnSnaIsT
2I1NtuijytGFaUHuS/ctW9F2xuL+5m6criMtokV1pT3CqGwl0D6DErDEGAAtzSdtQhv14R
npiazrKUgetQqtD6Awbx0pVukFpGUloAuVZMYhku1fbJNUCxCBZxC4StyDYWEFuQM+NwhJ
+mYogtY6BBLaw7DIq3AAABAE/cfAndWFb3Ri5leyUr8brc2wAZN3E1SfZ4MzII4jaUbUZe
2gqNN3v+iG7rDvC3eTbNUES7HexZNzcjRHgGEqbWOYhGKZpNtA1u8MLzf4NcywnrzwpNAd
Z00x+uWRF2oYOYMZklJtpFHodH8kkXV68ITErF/pXILzRADGuQkctqtCyg9MspSM2a6T9G
qZ+IFj4UNrRhL81wIRkdU288vdoCrhw0wylHNq320R52TiMW7XBqW3WEeVxM78koYbtuTJ
xnM9mUMKZ61d016HiPpSxeLzkiq+k8l5QVazc4/4Wz4XDluAzRXssLzlo8H9YuNDdVjs74
zye1QhfNFW8fpFgAAAEBAOkPqDYCTO2GDm/c3MkExBcywSxZmVHrVd8iX2uNrB7EEyk6Rp
ZKwVVZM6P2Ey5T31YreHSzLaBAdrXBKvUAQn8gYxo29lYE4dXXM8/sN+QEcogRS1HgAMgZ
6PDIyVknt5X85OqOtw0f8TrpPy9lIwVFlH869KffQNNt0fA0LXKn/hjY6EkgxCG+I5HMUe
WNstj2V2NQ7DaX6zmal+Vk4JIJvNj8Hb5Fe036M1zbgww/quhA0uPBT4BRnsK/gNE9/G05
+lP4PxoX3ff1w0Wd8LjAGbCfkcOhgcF+3FnnXD7eWJzkljnkDzxO2gctl1W824WuhCg+Ev
Jz4SsrHhUUQUcAAAEBAM3wqUpue9mSG53nrtJkLeaKpgun6RHPY/1BWSLIxGkPuUnnrX3V
bXJvV72hvPhQuJZv/xXq6DDkmDXX1DtM8YvQxeqWW01QUQYPx2Vr/mCcKoWsfRYOztgk8n
Gn1GoeCHXRBudmnQk/iEVEmhuizMFPzJri3J9ocwQATk/xzZs8D/2Gfv5wUF3ZJh1nXtVQ
55q6v+pRJjCJAXxCvVtIcsTFW1I1NiUMXxqbjRE9LGTBLT2mJta5TYB0RhPWZuNKoR+PSM
BrzjHsjPJylFBFXGFFiIZe8ld0HmdKe6MPg4ayvaIEnxdXg7Jb1tcO2ghEB+0C89nNkDhS
FAV7NIzFHQ8AAAARZ2l0aHViLWFjdGlvbi1rZXkBAg==
-----END OPENSSH PRIVATE KEY-----" > private_key.pem
        chmod 600 private_key.pem
        
        # Add the private key to the SSH agent
        ssh-add private_key.pem
        
        # Add the EC2 server's SSH fingerprint to known_hosts
        ssh-keyscan -H 50.112.216.238 >> ~/.ssh/known_hosts

    - name: Connect to EC2 and create test.txt
      run: |
        ssh -vvv -o StrictHostKeyChecking=no ubuntu@50.112.216.238 "echo 'I am a test file from GitHub Actions' > ~/test.txt"
