name: EC2 SSH Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH Agent
      run: |
        eval $(ssh-agent -s)
        
        # Write the private key to a file
        echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Add the private key to the SSH agent
        ssh-add private_key.pem
        
        # Add the EC2 server's SSH fingerprint to known_hosts
        ssh-keyscan -H 50.112.216.238 >> ~/.ssh/known_hosts
    - name: Connect to EC2 and create test.txt
      run: |
        ssh -vvv -o StrictHostKeyChecking=no ubuntu@50.112.216.238 "echo 'I am a test file from GitHub Actions' > ~/test.txt"
